# Generated by Django 5.2.6 on 2025-11-11 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["group_id", "user_id"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "address"], name="trip_place_name_dfec56_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TravelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_travel_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="travel_groups",
                        through="trip.GroupMember",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="groupmember",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_links",
                to="trip.travelgroup",
            ),
        ),
        migrations.CreateModel(
            name="TravelGroupPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "식당"),
                            ("CAFE", "카페"),
                            ("ATTRACTION", "어트랙션"),
                            ("SHOPPING", "쇼핑"),
                            ("PARK", "공원"),
                            ("MUSEUM", "박물관/전시"),
                            ("ACCOMMODATION", "숙소"),
                            ("OTHER", "기타"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_group_links",
                        to="trip.place",
                    ),
                ),
                (
                    "travel_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_links",
                        to="trip.travelgroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="travelgroup",
            name="places",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                through="trip.TravelGroupPlace",
                to="trip.place",
            ),
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="trip.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["place_id", "user_id"],
                "indexes": [
                    models.Index(
                        fields=["place", "user"], name="trip_recomm_place_i_41c090_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("place", "user"), name="uq_recommendation_place_user"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["group", "user"], name="trip_groupm_group_i_b26e25_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "user"), name="uq_membership_group_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="travelgroupplace",
            constraint=models.UniqueConstraint(
                fields=("travel_group", "place"), name="uq_membership_group_place"
            ),
        ),
    ]
