# Generated by Django 5.2.6 on 2025-10-22 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="place_type",
            field=models.CharField(
                choices=[
                    ("RESTAURANT", "식당"),
                    ("CAFE", "카페"),
                    ("ATTRACTION", "어트랙션"),
                    ("SHOPPING", "쇼핑"),
                    ("PARK", "공원"),
                    ("MUSEUM", "박물관/전시"),
                    ("ACCOMMODATION", "숙소"),
                    ("OTHER", "기타"),
                ],
                db_index=True,
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["group", "place_type"], name="trip_place_group_i_83fcdc_idx"
            ),
        ),
    ]
