# Generated by Django 5.2.6 on 2025-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="place",
            name="trip_place_name_dfec56_idx",
        ),
        migrations.AddField(
            model_name="place",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="place",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="place",
            name="lat",
            field=models.DecimalField(decimal_places=6, default=37.5665, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="place",
            name="lng",
            field=models.DecimalField(decimal_places=6, default=126.978, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["name"], name="trip_place_name_f91c8d_idx"),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["id"], name="trip_place_id_085688_idx"),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(fields=("id",), name="uq_place_id"),
        ),
    ]
